name: 'Gnocchi Container'
description: 'Run command inside Gnocchi Container'
author: 'Tobias Urdin'
inputs:
  command:
    description: 'Command to run'
    required: true
  debug:
    description: 'Debug output'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GNOCCHI_TEST_DEBUG: ${{ inputs.debug }}
  args:
    - ${{ inputs.command }}
